#-----------
#AUTOMATIONS
#-----------
automation:
  #------------------------------------------------------------------
  # Automatisering opties: alarm zoutmelding. 
  # vul je eigen mobile_app_iphone_van_xxx in. (als voorbeeld)            
  #------------------------------------------------------------------
    - id: salt_level_alarm_notify
    alias: Salt level alarm notify
    description: ''
    trigger:
    - platform: state
      entity_id: sensor.fill_salt
      to: "yes"
    condition:
    - condition: time
      after: 07:30:00
      before: '22:00:00'
    action:
    - service: notify.mobile_app_iphone_van_a_c_a
      data:
        title: Be aware!
        message: Salt level watersoftener is low! Fill salt today!
        data:
          push:
            sound:
              name: default
              critical: 1
              volume: 1
    initial_state: 'true'
    mode: single
  ##################################################