views:
  - title: Zoutniveau
    path: Zoutniveau
    badges: []
    cards:
      - type: entities
        entities:
          - entity: sensor.zoutniveau_afstand
            name: Afstand
          - entity: sensor.zoutniveau_hoogte
            name: Hoogte
          - entity: sensor.zoutniveau_procent
            name: Procent
          - entity: sensor.zout_bijvullen
      - type: entities
        entities:
          - entity: number.min_afstand_zout
          - entity: number.max_afstand_zout
          - entity: number.zout_bijvullen_afstand
          - entity: sensor.versie
          - entity: sensor.zoutniveau_ip
          - entity: sensor.wifi_signal
          - entity: sensor.wifi_signal_db
        title: Instellingen
      - elements:
          - entity: sensor.salt_level
            image: local/images/softener.png
            state_image:
              '0': local/images/softener0.png
              '10': local/images/softener10.png
              '20': local/images/softener20.png
              '40': local/images/softener40.png
              '60': local/images/softener60.png
              '80': local/images/softener80.png
              '100': local/images/softener100.png
            style:
              left: 0%
              top: 0%
              transform: scale(1,1)
            tap_action:
              action: none
            type: image
        image: local/images/softener.png
        panel: true
        type: picture-elements