views:
  - title: Saltlevel
    path: Saltlevel
    badges: []
    cards:
      - type: entities
        entities:
          - entity: sensor.saltlevel_distance
            name: Distance
          - entity: sensor.saltlevel_height
            name: Height
          - entity: sensor.saltlevel_procent
            name: Procent
          - entity: sensor.fill_salt
      - type: entities
        entities:
          - entity: number.min_distance_salt
          - entity: number.max_distance_salt
          - entity: sensor.fill_salt
          - entity: sensor.version
          - entity: sensor.salt_level_ip
          - entity: sensor.wifi_signal
          - entity: sensor.wifi_signal_db
        title: Settings
      - elements:
          - entity: sensor.salt_level
            image: local/images/softener.png
            state_image:
              '0': local/images/softener0.png
              '10': local/images/softener10.png
              '20': local/images/softener20.png
              '40': local/images/softener40.png
              '60': local/images/softener60.png
              '80': local/images/softener80.png
              '100': local/images/softener100.png
            style:
              left: 0%
              top: 0%
              transform: scale(1,1)
            tap_action:
              action: none
            type: image
        image: local/images/softener.png
        panel: true
        type: picture-elements