substitutions:
  name: zoutniveau
  friendly_name: Zoutniveau
  salt_level_distance: Zoutniveau afstand
  salt_level_procent: Zoutniveau procent
  salt_level_height: Zoutniveau hoogte
  salt_level_version: Versie
  salt_level_regeneration_last: Waterontharder geregenereerd op
  salt_level_fill_salt: Zout bijvullen
  salt_level_height_min: Min afstand zout
  salt_level_height_max: Max afstand zout
  salt_level_height_fill: Zout bijvullen afstand
  salt_level_ip: Zoutniveau IP
  salt_level_wifi_signal_db: WiFi Signaal dB
  salt_level_wifi_signal_db_percent: WiFi Signaal
  salt_level_uptime: Uptime
  hours: uur
  days: dagen
  salt_level_yes: ja
  salt_level_no: nee