substitutions:
  name: salt-level
  device_description: "Esphome component for Clack WS1 softener with ultrasonic sensor saltlevel detection"
  timezone: "Europe/Amsterdam"  

# In order to use other language or a different ESP chip, fix include file name below:
# Currently supported languages are en, nl. 
# ESP32 is a mh-et-live or wemos d32 mini, esp8266 is a wemos d1 mini, esp32s3 is a lilygo ESP32S3-T7,
# ESP32-wemos-s3 is a wemos S3 mini

packages:
  remote_package:
    url: https://github.com/fonske/Salt-level-ultrasonic
    ref: main
    files: 
      - esphome/.salt-level-labels-en.yaml
      # - esphome/.salt-level-labels-nl.yaml
      - esphome/board-esp32-wemos-s3.yaml
      # - esphome/board-esp8266.yaml

esphome:
  name: ${name}
  includes:
    - distance-sensor2.h
#  on_boot:
#    priority: 200
#    then:
#      - script.execute: on_boot

# Enable Home Assistant API
api:
  reboot_timeout: 0s

time:
  - platform: sntp
    id: salt_level_sntp_time
    timezone: ${timezone}

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} hotspot"
    password: "configesp"
    ap_timeout: 15s

